version: 0.1

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $REGION --no-include-email)
  build:
    commands:
      - docker build -t $REPOSITORY:$TAG .
      - docker tag $REPOSITORY:$TAG $ID.ecr.$REGION.amazonaws.com/$REPOSITORY:$TAG
    
  post_build:
    commands:
      - docker push $ID.ecr.$REGION.amazonaws.com/$REPOSITORY:$TAG
