// <auto-generated />
using System;
using FunLand.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunLand.Data.Migrations
{
    [DbContext(typeof(FunLandContext))]
    partial class FunLandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("FunLand.Data.Models.Blog", b =>
                {
                    b.Property<Guid>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(102400);

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("FunLand.Data.Models.BlogAttachment", b =>
                {
                    b.Property<int>("BlogAttachmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BlogId");

                    b.Property<string>("Path");

                    b.HasKey("BlogAttachmentId");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogAttachments");
                });

            modelBuilder.Entity("FunLand.Data.Models.BlogAttachment", b =>
                {
                    b.HasOne("FunLand.Data.Models.Blog")
                        .WithMany("BlogAttachments")
                        .HasForeignKey("BlogId");
                });
#pragma warning restore 612, 618
        }
    }
}
